# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 11:10
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_eml', models.EmailField(default='default@fme.com', max_length=50, null=True, verbose_name='Interact Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postalcode')),
                ('cp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cellphone')),
                ('landline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Landline')),
                ('usr_img', models.ImageField(blank=True, null=True, upload_to=website.models.GetPath, verbose_name='Profile Image')),
                ('privacy', models.CharField(choices=[('pub', 'Public'), ('pri', 'Private')], default='pub', max_length=3000, verbose_name='Privacy')),
                ('usrid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='EventInvitees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cm', 'Coming'), ('mb', 'Maybe'), ('nt', 'Next Time')], default='cm', max_length=100, verbose_name='Status')),
                ('date_invited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Invited')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('edate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('target_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Target')),
                ('status', models.CharField(choices=[('ong', 'On Going'), ('pas', 'Passed'), ('inc', 'Incoming')], default='pub', max_length=100, verbose_name='Status')),
                ('visibleto', models.CharField(choices=[('all', 'All'), ('fri', 'Only Friends'), ('fam', 'Family'), ('acq', 'Acquaintances')], default='public', max_length=100, verbose_name='Visible To')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftype', models.CharField(choices=[('fri', 'Friend'), ('fam', 'Family'), ('acq', 'Acquaintances')], default='fri', max_length=100, verbose_name='Friend Type')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Friend Since')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriends_friend_set', to=settings.AUTH_USER_MODEL, verbose_name='Friend')),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriends_usrid_set', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Wish')),
                ('desc', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('message', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Message')),
                ('alotted', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Alotted')),
                ('prod_link', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, verbose_name='Price')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events', verbose_name='Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventinvitees',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventinvitees',
            name='usrid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID'),
        ),
    ]
