"""
Django settings for fme project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k=8rg6jg4=03qno3kvls=s(*rsk7djbl51@w%#j8dmrlo93d)@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django', #<= Social sites signup
    'rest_framework', #<= API for phone app
    'website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware', #<= Social sites signup
]

ROOT_URLCONF = 'fme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(BASE_DIR), "website", "templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  #<= Social sites signup
                'social_django.context_processors.login_redirect', #<= Social sites signup
            ],
        },
    },
]

WSGI_APPLICATION = 'fme.wsgi.application'


AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth',      # for Google authentication
    'social_core.backends.google.GoogleOpenId',     # for Google authentication
    'social_core.backends.google.GoogleOAuth2',     # for Google authentication
    'social_core.backends.twitter.TwitterOAuth',    # for twitter authenication
    'social_core.backends.facebook.FacebookOAuth2', # for facebook authenication

    'django.contrib.auth.backends.ModelBackend',
)


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
#On successful login
LOGIN_REDIRECT_URL = 'index'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
USER_URL = os.path.join(STATIC_URL, "media", "users")
#STATIC_ROOT = os.path.join(BASE_DIR, "static", "static-only")
#MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")
#STATICFILES_DIRS = (os.path.join(BASE_DIR, "static", "static")),


if DEBUG:
    STATIC_URL = BASE_DIR + '/static/'
    MEDIA_URL = BASE_DIR + '/media/'
    USER_URL = os.path.join(STATIC_URL, "media", "users")
    STATIC_ROOT = os.path.join(BASE_DIR, "static", "static-only")
    MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")
    STATICFILES_DIRS = (os.path.join(BASE_DIR, "static", "static")),





#########################
### Social login auth ###
#########################

# !!!!! For development redirect is 'localhost:8000' on social sites, change to domain in production !!!!! 

#SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
# Google  !!!! Using jaguarcdm.test@gmail.com account !!!!
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='1094485690266-2u23bbp2vpbtku8mcq0vf32o3ug0ju2b.apps.googleusercontent.com' 
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'YeHS83cwZk8qaEWQk7a-6NHN'

# Facebook !!!! Using jaguarcdm.test@gmail.com account !!!!
SOCIAL_AUTH_FACEBOOK_KEY = '2027156584190178'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '10a93a8c7fc44b1457662a4d3870e3b9'  # App Secret


##############################
### SMTP server for Django ###
##############################
#For testing email on console use Django backend
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#For testing use Gmail
#For prodcustion maybe we can use somethiong like sendgrid

#SMTP server
EMAIL_HOST = 'smtp.gmail.com'

#Email@server.com
EMAIL_HOST_USER = 'Sarada@fme.com'

#Password
EMAIL_HOST_PASSWORD = 'sarada@123'

#TLS (secure) connection when talking to the SMTP server
EMAIL_USE_TLS = True
EMAIL_PORT = 587

#django-registration
ACCOUNT_ACTIVATION_DAYS = 5